services:
  - type: web
    name: bi-data-compare
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: streamlit run src/ui/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    healthCheckPath: /
